In [5]:
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime
import re
import json

url = 'https://www.tideschart.com/Indonesia/Jakarta/Weekly/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')


df_01 = list()
'''for el in soup.find("div",{"class" : "card-box card-bottom pb-0"}).find("script").find_all("tide"):
    #fic = text.get_text(",",strip=True)
    #print(fic)
    df_01.append(el.get_text(",{",strip=True).split(","))

df_01 = pd.DataFrame(df_01)'''


import requests
headers =   {'user-agent':'Mozilla/5.0'}

page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.content)
tes1 = soup.find("div",{"class" : "card-box card-bottom pb-0"}).find("script")
#print(soup.select_one("script:contains('title')"))

data = re.search(r"tideData = (.*});", tes1.string , flags=re.S).group(1)
data = json.loads(data)
print(data["data1 "][0]["tide"])

display(df_01)

C:\Users\P5CD1\AppData\Local\Temp\ipykernel_1072\1734708317.py:22: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options = chrome_options)

AttributeError: 'NoneType' object has no attribute 'group'

In [15]:
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime
import re
import json

url = 'https://www.tideschart.com/Indonesia/Jakarta/Weekly/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')

import requests, re, json

pattern = re.compile(r'data1 = ({.*})$', re.MULTILINE | re.DOTALL)
script = soup.find("script", text=pattern)

json_string = pattern.search(script.get_text()).group(1)
data = json.loads(json_string)
'''
r = requests.get('https://www.tideschart.com/Indonesia/Jakarta/Weekly/').text
json_data = json.loads(re.search(r"data1 = ({.*})$", r).group(1))

json_data['tide']

const tideData = (data1 = {title: "Daerah Khusus Ibukota Jakarta's tide times for 10 Jan - 16 Jan",unit: "m",
        currentDate: "2023-01-10",
        currentTime: "16:59",
        tide: [{date: "2023-01-09", time: "23:36", value: 0.3 }, { date: "2023-01-10", time: "10:49", value: 1 }, { date: "2023-01-10", time: "22:02", value: 0.3 }, { date: "2023-01-11", time: "10:54", value: 1 }, { date: "2023-01-11", time: "22:15", value: 0.3 }, { date: "2023-01-12", time: "10:47", value: 0.9 }, { date: "2023-01-12", time: "22:13", value: 0.4 }, { date: "2023-01-13", time: "10:16", value: 0.8 }, { date: "2023-01-13", time: "21:44", value: 0.4 }, { date: "2023-01-14", time: "09:10", value: 0.8 }, { date: "2023-01-14", time: "20:33", value: 0.4 }, { date: "2023-01-15", time: "08:02", value: 0.8 }, { date: "2023-01-15", time: "18:36", value: 0.4 }, { date: "2023-01-16", time: "07:31", value: 0.9 }, { date: "2023-01-16", time: "17:36", value: 0.3 }, { date: "2023-01-17", time: "00:10", value: 0.9 }], sun: [{ date: "2023-01-10", sunrise: "05:47", sunset: "18:14" },{ date: "2023-01-11", sunrise: "05:47", sunset: "18:14" },{ date: "2023-01-12", sunrise: "05:48", sunset: "18:14" },{ date: "2023-01-13", sunrise: "05:48", sunset: "18:15" },{ date: "2023-01-14", sunrise: "05:49", sunset: "18:15" },{ date: "2023-01-15", sunrise: "05:49", sunset: "18:15" },{ date: "2023-01-16", sunrise: "05:50", sunset: "18:15" }],
      });

      new VisTideChart({
        id: "tide-chart-container",
        data: tideData,
      });	  '''

C:\Users\P5CD1\AppData\Local\Temp\ipykernel_10960\52803275.py:22: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options = chrome_options)

AttributeError: 'NoneType' object has no attribute 'get_text'

In [ ]:
import requests, json
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime

#r= requests.get("https://www.tideschart.com/Indonesia/Jakarta/Weekly/")
#c= r.content
#soup= BeautifulSoup(c, "html.parser")

url= requests.get("https://www.tideschart.com/Indonesia/Jakarta/Weekly/")

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')

df_01 = list()
for el in soup.find("div",{"class" : "card-box card-bottom pb-0"}).find_all("script"):
    #fic = el.get_text(",",strip=True)
    fic = el.get_text("{", strip = True)
    
    fic = fic[fic.find('{date:'):]
    sep = ' }],'
    fic = fic.split(sep, 1)[0]
    #print(fic)
    #df_01.append(el.get_text(",{",strip=True).split(","))
    #df_01.append(el.get_text("{", strip = True).split(","))
    #df_01 = pd.DataFrame(fic)
    s = fic
    s = re.findall(r'\d+', s)
    #print(fic)
    print(s)
    #s = json.loads(s)
    #print(type(s))

import numpy as np
array_results=np.array(s)
#df_02=pd.DataFrame(array_results.reshape(2, len(s)))
#df_01 = pd.DataFrame(s)
#display(df_02)

In [23]:
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime
import re
import json
import numpy as np

url = 'https://www.tideschart.com/Indonesia/Jakarta/Weekly/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')


#df_01 = list()
for el in soup.find("div",{"class" : "card-box card-bottom pb-0"}).find_all("script"):
    #fic = el.get_text(",",strip=True)
    fic = el.get_text("{", strip = True)
    
    fic = fic[fic.find('{date:'):]
    sep = ' }],'
    fic = fic.split(sep, 1)[0]
    #print(fic)
    #df_01.append(el.get_text(",{",strip=True).split(","))
    #df_01.append(el.get_text("{", strip = True).split(","))
    #df_01 = pd.DataFrame(fic)
    s = fic
    
    s = re.findall(r'\d+', s)
    #s = ''.join(s)
    #print(fic)
    print(s)
    
    #s = json.loads(s)
    #print(type(s))
for element in s:
    print(f"I bought {element}!")

df_01 = pd.DataFrame(data = s, dtype=np.int8)
display(df_01)

C:\Users\P5CD1\AppData\Local\Temp\ipykernel_1072\4166599033.py:23: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options = chrome_options)

['2023', '01', '10', '23', '33', '0', '3', '2023', '01', '11', '10', '54', '1', '2023', '01', '11', '22', '15', '0', '3', '2023', '01', '12', '10', '47', '0', '9', '2023', '01', '12', '22', '13', '0', '4', '2023', '01', '13', '10', '16', '0', '8', '2023', '01', '13', '21', '44', '0', '4', '2023', '01', '14', '09', '10', '0', '8', '2023', '01', '14', '20', '33', '0', '4', '2023', '01', '15', '08', '02', '0', '8', '2023', '01', '15', '18', '36', '0', '4', '2023', '01', '16', '07', '31', '0', '9', '2023', '01', '16', '17', '36', '0', '3', '2023', '01', '17', '07', '31', '1', '2023', '01', '17', '17', '30', '0', '2', '2023', '01', '18', '00', '10', '1']
[]

Empty DataFrame
Columns: []
Index: []

In [42]:
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime
import re
import json
import numpy as np

url = 'https://www.tideschart.com/Indonesia/Jakarta/Weekly/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')

fic = soup.select_one("script:contains('data1')")
fic = fic.get_text("{", strip = True)
fic = fic[fic.find('{date:'):]
sep = ' }],'
fic = fic.split(sep, 1)[0]
    #print(fic)
    #df_01.append(el.get_text(",{",strip=True).split(","))
    #df_01.append(el.get_text("{", strip = True).split(","))
    #df_01 = pd.DataFrame(fic)
s = fic
    
s = re.findall(r'\d+', s)
    #s = ''.join(s)
    #print(fic)
print(s)
df_02 = pd.DataFrame(s)
#print(fic)
display(df_02)

C:\Users\P5CD1\AppData\Local\Temp\ipykernel_1072\44269277.py:23: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options = chrome_options)

['2023', '01', '10', '23', '33', '0', '3', '2023', '01', '11', '10', '54', '1', '2023', '01', '11', '22', '15', '0', '3', '2023', '01', '12', '10', '47', '0', '9', '2023', '01', '12', '22', '13', '0', '4', '2023', '01', '13', '10', '16', '0', '8', '2023', '01', '13', '21', '44', '0', '4', '2023', '01', '14', '09', '10', '0', '8', '2023', '01', '14', '20', '33', '0', '4', '2023', '01', '15', '08', '02', '0', '8', '2023', '01', '15', '18', '36', '0', '4', '2023', '01', '16', '07', '31', '0', '9', '2023', '01', '16', '17', '36', '0', '3', '2023', '01', '17', '07', '31', '1', '2023', '01', '17', '17', '30', '0', '2', '2023', '01', '18', '00', '10', '1']

        0
0    2023
1      01
2      10
3      23
4      33
..    ...
104    01
105    18
106    00
107    10
108     1

[109 rows x 1 columns]

In [103]:
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime
import re
import json
import numpy as np

url = 'https://www.tideschart.com/Indonesia/Jakarta/Weekly/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')

fic = soup.select_one("script:contains('data1')")
fic = fic.get_text("{", strip = True)
#print(fic)
fic = fic[fic.find('{date:'):]
sep = '],'
fic = fic.split(sep, 1)[0]
#print(fic)

#pattern = r'"([A-Za-z0-9_\./\\-]*)"'
pattern_tanggal_waktu = r'"(.*?)"'
tanggal_waktu_raw = re.findall(pattern_tanggal_waktu, fic)
#print(tanggal_waktu_raw)

#pattern_value_tide = r"[-+]?(?:\d*\.*\d+)"
pattern_value_tide = r'(?<=value\:\s)(?:\d*\.*\d+)'
value_tide_raw = re.findall(pattern_value_tide, fic)
#print(value_tide_raw)
#fic = list(fic)

df_01 = pd.DataFrame(tanggal_waktu_raw)
df_01 = df_01.tail(df_01.shape[0]-2)
df_01 = df_01.head(df_01.shape[0]-2)
df_01.index = range(len(df_01))
#display(df_01)

df_02 = pd.DataFrame(value_tide_raw)
df_02 = df_02.tail(df_02.shape[0]-1)
df_02 = df_02.head(df_02.shape[0]-1)
df_02.index = range(len(df_02))
#display(df_02)

C:\Users\P5CD1\AppData\Local\Temp\ipykernel_1072\782958903.py:23: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options = chrome_options)

In [104]:

df_01['tanggal'] = ''
display(df_01)

i = 0
j = 0
k = 1

while i <= 13:
    df_01.loc[i, 'tanggal'] = df_01.iloc[j,0] + ' ' + df_01.iloc[k,0]
    i += 1
    j += 2
    k += 2
'''df_01.loc[0, 'tanggal'] = df_01.iloc[0,0] + ' ' + df_01.iloc[1,0]
df_01.loc[1, 'tanggal'] = df_01.iloc[2,0] + ' ' + df_01.iloc[3,0]
df_01.loc[2, 'tanggal'] = df_01.iloc[4,0] + ' ' + df_01.iloc[5,0]'''

df_01 = df_01.drop(df_01.columns[[0]], axis=1)
df_01 = df_01.drop(labels = [14,15,16,17,18,19,20,21,22,23,24,25,26,27], axis = 0)
df_01.index = range(len(df_01))
display(df_01)
#df_01.iloc['tanggal'] = pd.to_datetime(df_01['tanggal'])
#display(df_01)

             0 tanggal
0   2023-01-11
1        10:54
2   2023-01-11
3        22:15
4   2023-01-12
5        10:47
6   2023-01-12
7        22:13
8   2023-01-13
9        10:16
10  2023-01-13
11       21:44
12  2023-01-14
13       09:10
14  2023-01-14
15       20:33
16  2023-01-15
17       08:02
18  2023-01-15
19       18:36
20  2023-01-16
21       07:31
22  2023-01-16
23       17:36
24  2023-01-17
25       07:31
26  2023-01-17
27       17:30

             tanggal
0   2023-01-11 10:54
1   2023-01-11 22:15
2   2023-01-12 10:47
3   2023-01-12 22:13
4   2023-01-13 10:16
5   2023-01-13 21:44
6   2023-01-14 09:10
7   2023-01-14 20:33
8   2023-01-15 08:02
9   2023-01-15 18:36
10  2023-01-16 07:31
11  2023-01-16 17:36
12  2023-01-17 07:31
13  2023-01-17 17:30

In [106]:
df_01['tanggal'] = pd.to_datetime(df_01['tanggal'])
display(df_01)

               tanggal
0  2023-01-11 10:54:00
1  2023-01-11 22:15:00
2  2023-01-12 10:47:00
3  2023-01-12 22:13:00
4  2023-01-13 10:16:00
5  2023-01-13 21:44:00
6  2023-01-14 09:10:00
7  2023-01-14 20:33:00
8  2023-01-15 08:02:00
9  2023-01-15 18:36:00
10 2023-01-16 07:31:00
11 2023-01-16 17:36:00
12 2023-01-17 07:31:00
13 2023-01-17 17:30:00

In [108]:
df_02 = df_02.rename(columns={0: 'Value_tide'})
display(df_02)

   Value_tide
0           1
1         0.3
2         0.9
3         0.4
4         0.8
5         0.4
6         0.8
7         0.4
8         0.8
9         0.4
10        0.9
11        0.3
12          1
13        0.2

In [115]:
df_01['Datetime_tide1'] = ''
df_01['Datetime_tide2'] = ''

x = 0
y = 0
z = 1
while x <= 6:
    df_01.loc[x, 'Datetime_tide1'] = df_01.iloc[y,0]
    df_01.loc[x, 'Datetime_tide2'] = df_01.iloc[z,0]
    x += 1
    y += 2
    z += 2


display(df_01)

               tanggal       Datetime_tide1       Datetime_tide2
0  2023-01-11 10:54:00  2023-01-11 10:54:00  2023-01-11 22:15:00
1  2023-01-11 22:15:00  2023-01-12 10:47:00  2023-01-12 22:13:00
2  2023-01-12 10:47:00  2023-01-13 10:16:00  2023-01-13 21:44:00
3  2023-01-12 22:13:00  2023-01-14 09:10:00  2023-01-14 20:33:00
4  2023-01-13 10:16:00  2023-01-15 08:02:00  2023-01-15 18:36:00
5  2023-01-13 21:44:00  2023-01-16 07:31:00  2023-01-16 17:36:00
6  2023-01-14 09:10:00  2023-01-17 07:31:00  2023-01-17 17:30:00
7  2023-01-14 20:33:00
8  2023-01-15 08:02:00
9  2023-01-15 18:36:00
10 2023-01-16 07:31:00
11 2023-01-16 17:36:00
12 2023-01-17 07:31:00
13 2023-01-17 17:30:00

In [118]:
df_01 = df_01.drop(df_01.columns[[0]], axis=1)
df_01 = df_01.drop(labels = [7,8,9,10,11,12,13], axis = 0)
df_01.index = range(len(df_01))
display(df_01)

KeyError: '[7, 8, 9, 10, 11, 12, 13] not found in axis'

In [8]:
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from pathlib import Path
from IPython.display import display
from sqlalchemy import create_engine
import datetime
import re
import json
import numpy as np

url = 'https://www.tideschart.com/Indonesia/Jakarta/Weekly/'

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
chrome_options.add_argument(f'user-agent={user_agent}')

driver = webdriver.Chrome(chrome_options = chrome_options)

time.sleep(0.5)
driver.get(url)
time.sleep(0.5)

soup = BeautifulSoup(driver.page_source, 'lxml')

fic = soup.select_one("script:contains('data1')")
fic = fic.get_text("{", strip = True)
#print(fic)
fic = fic[fic.find('{date:'):]
sep = '],'
fic = fic.split(sep, 1)[0]
#print(fic)

#pattern = r'"([A-Za-z0-9_\./\\-]*)"'
pattern_tanggal_waktu = r'"(.*?)"'
tanggal_waktu_raw = re.findall(pattern_tanggal_waktu, fic)
#print(tanggal_waktu_raw)

#pattern_value_tide = r"[-+]?(?:\d*\.*\d+)"
pattern_value_tide = r'(?<=value\:\s)(?:\d*\.*\d+)'
value_tide_raw = re.findall(pattern_value_tide, fic)
#print(value_tide_raw)
#fic = list(fic)

df_01 = pd.DataFrame(tanggal_waktu_raw)
df_01 = df_01.tail(df_01.shape[0]-2)
df_01 = df_01.head(df_01.shape[0]-2)
df_01.index = range(len(df_01))
#display(df_01)

df_02 = pd.DataFrame(value_tide_raw)
df_02 = df_02.tail(df_02.shape[0]-1)
df_02 = df_02.head(df_02.shape[0]-1)
df_02.index = range(len(df_02))
#display(df_02)

df_01['tanggal'] = ''
#display(df_01)

i = 0
j = 0
k = 1

while i <= 13:
    df_01.loc[i, 'tanggal'] = df_01.iloc[j,0] + ' ' + df_01.iloc[k,0]
    i += 1
    j += 2
    k += 2

df_01 = df_01.drop(df_01.columns[[0]], axis=1)
df_01 = df_01.drop(labels = [14,15,16,17,18,19,20,21,22,23,24,25,26,27], axis = 0)
df_01.index = range(len(df_01))
#display(df_01)

df_01['tanggal'] = pd.to_datetime(df_01['tanggal'])

df_02 = df_02.rename(columns={0: 'Value_tide'})

df_01['Datetime_tide1'] = ''
df_01['Datetime_tide2'] = ''

x = 0
y = 0
z = 1
while x <= 6:
    df_01.loc[x, 'Datetime_tide1'] = df_01.iloc[y,0]
    df_01.loc[x, 'Datetime_tide2'] = df_01.iloc[z,0]
    x += 1
    y += 2
    z += 2

df_01 = df_01.drop(df_01.columns[[0]], axis=1)
df_01 = df_01.drop(labels = [7,8,9,10,11,12,13], axis = 0)
df_01.index = range(len(df_01))

df_02['tide1'] = ''
df_02['tide2'] = ''

x = 0
y = 0
z = 1
while x <= 6:
    df_02.loc[x, 'tide1'] = df_02.iloc[y,0]
    df_02.loc[x, 'tide2'] = df_02.iloc[z,0]
    x += 1
    y += 2
    z += 2

df_02 = df_02.drop(df_02.columns[[0]], axis=1)
df_02 = df_02.drop(labels = [7,8,9,10,11,12,13], axis = 0)
df_02.index = range(len(df_02))

#display(df_02)
#display(df_01)

df_all = []
df_all = pd.DataFrame(df_all, columns =[
    "Datetime_taken",
    "Datetime_tide1",
    "tide1",
    "Datetime_tide2",
    "tide2"
]
)


df_all['Datetime_tide1'] = df_01['Datetime_tide1']
df_all['tide1'] = df_02['tide1']
df_all['Datetime_tide2'] = df_01['Datetime_tide2']
df_all['tide2'] = df_02['tide2']

df_all.tide1 = pd.to_numeric(df_all.tide1, errors='coerce')
df_all.tide2 = pd.to_numeric(df_all.tide2, errors='coerce')

df_all['Datetime_taken'] = datetime.datetime.now()

#display(df_all)

df_all_1 = df_all.drop(labels = [1,2,3,4,5,6], axis = 0)
df_all_1.index = range(len(df_all_1))
#display(df_all_1)
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

hostname="localhost"
dbname="workshop"
uname="root"
pwd="sanjii123"

engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}"
				.format(host=hostname, db=dbname, user=uname, pw=pwd))

session = sessionmaker(bind=engine)()
                               
df_all_1.to_sql('table_parsing_tides_coba_current', engine, if_exists='replace', index=False)
df_all_1.to_sql('table_parsing_tides_coba_hystorian', engine, if_exists='append', index=False)
df_all.to_sql('table_parsing_un_tides_coba_current', engine, if_exists='replace', index=False)
df_all.to_sql('table_parsing_un_tides_coba_hystorian', engine, if_exists='append', index=False)


engine.dispose()
session.close()


driver.quit()

C:\Users\P5CD1\AppData\Local\Temp\ipykernel_4604\2412166584.py:23: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options = chrome_options)

In [9]:
display(df_all_1)

,Datetime_taken,Datetime_tide1,tide1,Datetime_tide2,tide2
0,2023-01-15 18:42:01.110263,2023-01-15 08:02:00,0.8,2023-01-15 18:36:00,0.4